services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vinay@data55
      MYSQL_DATABASE: worldbank_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./Deploy/Dockerfile.run-backend
    container_name: backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: Vinay@data55
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/worldbank_db?allowPublicKeyRetrieval=true&useSSL=false
    restart: always

volumes:
  mysql_data:
