# This Dockerfile runs the built Spring Boot JAR file
FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY ../Backend/build/libs/WorldBankDevIndApplication-0.0.1-SNAPSHOT.jar ./app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
